#!/usr/bin/env python3
"""Map `knowledge/09-raw/a11-sources.yaml` to `lake/sources.yaml` (spec 10 §4.1).

Run: `python3 tools/gen_sources.py`. Deterministic: a second run rewrites the
same bytes, so it is safe to re-run after the corpus file is edited.

Two things the mapper does NOT invent:

* `url` and `version` of a `Source` (§1.1). Neither exists in the corpus file;
  both come from the arXiv API at fetch time, where `fetch_metadata()` already
  returns the versioned id and `updated` (`09-raw/fetch_arxiv_sections.py:26-37`).
  So arXiv rows carry no `url`/`version` key at all — `ingest/fetch.py` fills them.
* Anything for non-arXiv rows beyond what the corpus states. `arxiv_id: null`
  rows carry their own `url`; the one row that has only a DOI gets the canonical
  `https://doi.org/<doi>` form (§1.1) plus an explicit `skip` reason, because
  none of the three §4.2 fetch paths (arxiv html → ar5iv → arXiv PDF) can reach it.

`group`, `html`, `why`, `survey`, `fresh` are kept here and go **no further**:
they never reach the `Source` node — `06:237`, "Домен — не сущность. Ни таблицы,
ни поля, ни фильтра". They stay because they are the human record of why each
of the checked entries is in the corpus.

`kind` is renamed to `type` to match `Source.type` (§1.1: "Против 06 §3.2:
`kind` → `type`"); values are unchanged (`paper` | `doc`; `run` only comes from C).
"""
import collections
import hashlib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "knowledge" / "09-raw" / "a11-sources.yaml"
OUT = ROOT / "lake" / "sources.yaml"

# §4.1 quotes `09:301-306` for the corpus composition. Counts are printed against
# these, not asserted against them: the corpus file is the ground truth.
SPEC_GROUPS = {"evo_search": 27, "agentic_pipelines": 25, "cheap_proxies": 20, "memory": 13}
SPEC_TOTAL = 84  # §4.1 / `09:299`

HEADER = """\
# Corpus of the write path (spec 10 §4.1). GENERATED by tools/gen_sources.py
# from knowledge/09-raw/a11-sources.yaml — edit that file, then re-run, do not
# edit this one by hand.
#
# `url` and `version` of arXiv rows are absent on purpose: ingest/fetch.py takes
# both from the arXiv API (fetch_metadata() returns the versioned id and updated,
# 09-raw/fetch_arxiv_sections.py:26-37).
#
# `type` is Source.type (§1.1), renamed from the corpus field `kind`.
# `skip` — this row cannot be fetched; the value is the reason. fetch.py must
# skip it explicitly and never guess a URL for it.
#
# `group`, `html`, `why`, `survey`, `fresh` live ONLY in this file and are never
# written to the Source node: 06:237 — "Домен — не сущность. Ни таблицы, ни поля,
# ни фильтра".
"""


def convert(raw: dict) -> dict:
    """One corpus record -> one sources.yaml record."""
    entry: dict = {"arxiv_id": raw["arxiv_id"]}

    if raw["arxiv_id"] is None:
        url = raw.get("url")
        if url:
            entry["url"] = url
        elif raw.get("doi"):
            # §1.1: DOI is carried as its canonical https://doi.org/... address.
            entry["url"] = "https://doi.org/" + raw["doi"]
            entry["skip"] = (
                "no arXiv id, DOI landing page only: none of the three §4.2 fetch "
                "paths (arxiv html -> ar5iv -> arXiv PDF) can reach the full text"
            )
        else:
            raise ValueError(f"non-arXiv entry with neither url nor doi: {raw['title']!r}")

    entry["title"] = raw["title"]
    entry["type"] = raw["kind"]
    if entry["type"] not in ("paper", "doc"):
        raise ValueError(f"unexpected kind {raw['kind']!r} in {raw['title']!r}")
    entry["year"] = raw["year"]
    for key in ("group", "html", "survey", "fresh"):
        if key in raw:
            entry[key] = raw[key]
    entry["why"] = raw["why"]
    return entry


def dump(entries: list[dict]) -> str:
    # width: never fold a `why` line — a folded plain scalar re-reads with its line
    # break turned into a space, which would silently rewrite the text.
    return HEADER + yaml.safe_dump(
        entries, sort_keys=False, allow_unicode=True, default_flow_style=False, width=10**6
    )


def main() -> None:
    corpus = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    entries = [convert(raw) for raw in corpus]
    text = dump(entries)
    # --- checks: the mapper is the only thing standing between a hand-checked
    # corpus and the ingest run, so it verifies its own output before reporting.
    # Written to a temp file first and moved into place only once the checks pass:
    # writing straight to OUT left an unvalidated corpus on disk whenever a check
    # tripped. `raise`, not `assert` — `python3 -O` strips asserts and exits 0.
    tmp = OUT.with_suffix(".yaml.tmp")
    tmp.write_text(text, encoding="utf-8")

    reloaded = yaml.safe_load(tmp.read_text(encoding="utf-8"))
    if reloaded != entries:
        tmp.unlink()
        raise ValueError("round-trip through YAML changed the records")

    counts = collections.Counter(e["group"] for e in entries)
    if set(counts) != set(SPEC_GROUPS):
        tmp.unlink()
        raise ValueError(f"groups {sorted(counts)} vs §4.1 {sorted(SPEC_GROUPS)}")

    tmp.replace(OUT)

    print(f"{OUT.relative_to(ROOT)}: {len(entries)} entries, md5 {hashlib.md5(text.encode()).hexdigest()}")
    if len(entries) != SPEC_TOTAL:
        print(f"  MISMATCH total: corpus {len(entries)} vs §4.1 {SPEC_TOTAL}")
    for group, spec_n in SPEC_GROUPS.items():
        mark = "" if counts[group] == spec_n else f"  <-- MISMATCH vs §4.1 {spec_n}"
        print(f"  {group:<18} {counts[group]}{mark}")
    by_type = collections.Counter(e["type"] for e in entries)
    print(f"  types {dict(by_type)}, non-arXiv {sum(1 for e in entries if not e['arxiv_id'])}, "
          f"skipped {sum(1 for e in entries if 'skip' in e)}")
    for e in entries:
        if "skip" in e:
            print(f"  skip: {e['title'][:60]!r} — {e['skip']}")


if __name__ == "__main__":
    main()
